### ISSUE TITLE
Fejl ved Auto Update ifm FOT link fejl

### ISSUE THREAD

**Issue by AnetteKlinker** [geodatastyrelsen/stedfinder#17]
Ved Auto Update af multipolygoner bliver stednavnet placeret på den mindste polygon, og kun dér.

**Comment by steenhulthin** [comment]
This bug is not related to "stedfinder".

**Comment by AnetteKlinker** [comment]
Ok - så må du hjælpe mig med hvor jeg s skal oprette den :o)
Vh
Anette Klinker
B3.15

Fra: Steen Hulthin Rasmussen [mailto:notifications@github.com]
Sendt: 6. januar 2016 08:59
Til: geodatastyrelsen/stedfinder
Cc: Anette Klinker
Emne: Re: [stedfinder] Fejl ved Auto Update ifm FOT link fejl (#17)


This bug is not related to "stedfinder".
